# Development Application Configuration
application:
  name: DevOpsSimulator
  version: 2.0.0-beta
  environment: development
  
server:
  host: localhost
  port: 3000
  ssl_enabled: false
  hot_reload: true
  
logging:
  level: DEBUG
  format: pretty
  output: console
  show_stack_trace: true
  
database:
  host: localhost
  port: 5432
  name: devops_dev
  
features:
  auto_scaling: false
  load_balancer: disabled
  backup_enabled: false
  experimental_features: true
  
development:
  mock_external_apis: true
  debug_mode: true
  cors_enabled: true
  
notifications:
  slack_webhook: "https://hooks.slack.com/services/XXX"
  discord_webhook: "https://discord.com/api/webhooks/YYY"
  email_alerts: false

# --- Experimental Features (from conflict-simulator) ---
# The following configurations are for experimental mode and are not active.

# ai_features:
#   predictive_scaling: true
#   anomaly_detection: true
#   auto_optimization: true
#   model_version: "v2.1.0"
# 
# cloud_providers:
#   - aws
#   - azure
#   - gcp
#   - digitalocean
# 
# security:
#   zero_trust: enabled
#   encryption: AES-256
#   audit_logging: comprehensive